{
 "title": "Linkhub metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Signal Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mobile. Network Signal Strength",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "signal_strength" }
   ]
  },
  {
   "title": "Network connectivity tracking",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "network_info_info", "legendFormat": "{{network_name}} / {{cell_id}}" }
   ]
  },
  {
   "title": "Signal to Interference plus Noise Ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    { "expr": "sinr" },
    { "expr": "avg_over_time(sinr[5m])", "legendFormat": "Average SINR over 5mins" }
   ]
  },
  {
   "title": "Reference Signal Received Quality",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    { "expr": "rsrq" }
   ]
  },
  {
   "title": "Reference Signal Received Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    { "expr": "rsrp" }
   ]
  },
  {
   "title": "Received Signal Strength Indicator",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    { "expr": "rssi" }
   ]
  },
  { "title": "Network Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Data transfer metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "total_download_this_month" },
    { "expr": "total_upload_this_month" }
   ]
  },
  {
   "title": "Number of connected devices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    { "expr": "connected_devices" }
   ]
  },
  { "title": "Misc Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Box Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "connection_time" }
   ]
  }
 ]
}