
name: Deployment

on:
  workflow_run:
    branches: master
    workflows:
      - Python
    types:
      - completed

jobs:
  publish:
    name: "Publish to PyPI"
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.ref_type	 == 'tag'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Publish
        run: |
          python -m pip install --upgrade pip
          python -m pip install 'poetry>=1.2.0b1'
          poetry plugin add poetry-dynamic-versioning-plugin
          poetry publish --no-interaction --build --username __token__ --password ${{ secrets.PYPI_DEPLOY_TOKEN }}